config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :rentals

end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :rentals, dependent: :destroy

end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :client
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:avatar, :name, :email)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:image, :name)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: %i[ show edit update destroy ]

  # GET /rentals or /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1 or /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals or /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully created." }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1 or /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to rental_url(@rental), notice: "Rental was successfully updated." }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1 or /rentals/1.json
  def destroy
    @rental.destroy

    respond_to do |format|
      format.html { redirect_to rentals_url, notice: "Rental was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rental_params
      params.require(:rental).permit(:client_id, :movie_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/clients/_client.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 20vh;">
  <div class="container">
  
    <div id="<%= dom_id(client) %>">
      <p class="text-center">
        <strong>Avatar:</strong>
        <img src="<%= client.avatar %>" alt="Avatar" style="width: 50px;">
      </p>

      <p class="text-center">
        <strong>Name:</strong>
        <%= client.name %>
      </p>

      <p class="text-center">
        <strong>Email:</strong>
        <%= client.email %>
      </p>
    </div>
  </div>
</div>

app/views/clients/_form.html.erb
<div class="d-flex justify-content-center">
  <div class="card" style="width: 300px;">
    <div class="card-body">
      <h5 class="card-title"></h5>

      <%= form_with(model: client, local: true) do |form| %>
        
        <div class="form-group">
          <%= form.label :avatar %>
          <%= form.text_field :avatar, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.email_field :email, class: "form-control" %>
          <br> <br>
        </div>

        <div class="d-flex justify-content-between">
          <%= form.submit "Guardar", class: "btn btn-primary" %>
          <%= link_to "Cancelar", clients_path, class: "btn btn-secondary" %>
        </div>
      <% end %>

      
    </div>
  </div>
</div>

app/views/clients/edit.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="container">
    <h1 class="text-center">Editar Cliente</h1>

    <%= render "form", client: @client %>

    <br>

  
  </div>
</div>
 

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Clientes de Blockbuster</h1>

<%= link_to "Agregar nuevo cliente", new_client_path, class: "btn btn-success float-right mb-3" %>



<div class="d-flex justify-content-center">
  <div class="row justify-content-center align-items-center no-gutters">
    <% @clients.each do |client| %>
      <div class="col-lg-2 px-">
        <div class="card" style="width: 90%;">
          <img src="<%= client.avatar %>" class="card-img-top" alt="Avatar">
          <div class="card-body">
            <h6 class="card-title">Cliente: <%= client.name %></h6>
            <p class="card-text">
              <span class="font-weight-bold">Correo:</span> <%= client.email %>
            </p>
            <a href="<%= edit_client_path(client) %>" class="btn btn-primary btn-sm">Editar</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title text-center">Nuevo Cliente</h1>

          <%= render "form", client: @client %>
        </div>
      </div>
    </div>
  </div>
</div>


 

app/views/clients/show.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="container">


   

<p style="color: green"><%= notice %></p>


 <h1 class="text-center">Cliente</h1>


<%= render @client %>

    <div class="d-flex justify-content-center">

  <%= button_to "Eliminar Cliente", @client, method: :delete, class: "btn btn-secondary"%>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBusterRm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>


  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  
  </head>

  <body>
  
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">BlockBuster</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Clientes", clients_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Películas", movies_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Rentas", rentals_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>




    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="d-flex justify-content-center">
  <div class="card" style="width: 300px;">
    <div class="card-body">
      <h5 class="card-title"></h5>

      <%= form_with(model: @movie) do |form| %>
        <% if @movie.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

            <ul>
              <% movie.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :image, "Imagen URL", style: "display: block"  %>
          <%= form.text_field :image, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :name, "Nombre de la Pelicula", style: "display: block" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

       
        <div class="d-flex justify-content-between">
          <%= form.submit "Guardar", class: "btn btn-primary" %>
          <%= link_to "Cancelar", movies_path, class: "btn btn-secondary" %>
        </div>
      <% end %>
    
    </div>
  </div>
</div>

app/views/movies/_movie.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 20vh;">
  <div class="container">
  

<div id="<%= dom_id movie %>">
  <p>
    <strong>Imagen:</strong>
    <img src="<%= movie.image %>" alt="Pelicula" style="width: 50px;">
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= movie.name %>
  </p>

</div>

</div>
</div>

app/views/movies/edit.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="container">
    <h1 class="text-center">Editar Pelicula </h1>

<%= render "form", movie: @movie %>


  </div>
</div>
 

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Peliculas de Nuestra Base de Datos</h1>

<%= link_to "Agregar nueva película", new_movie_path, class: "btn btn-success float-right mb-3" %>







<div class="d-flex justify-content-center">
  <div class="row justify-content-center align-items-center no-gutters">
    <% @movies.each do |movie| %>
      <div class="col-lg-2 px-">
        <div class="card" style="width: 90%;">
          <img src="<%=  movie.image %>" class="card-img-top" alt="Pelicula">
          <div class="card-body">
            <h6 class="card-title">Pelicula: <%=  movie.name %></h6>
            
            </p>
            <a href="<%= edit_movie_path(movie) %>" class="btn btn-primary btn-sm">Editar</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/new.html.erb
 <div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">

        
          <h1 class="card-title text-center">Nueva Pelicula</h1>

          <%= render "form", client: @movie %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
 
  <div class="container">


<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>  
  <%= button_to "Eliminar Pelicula", @movie, method: :delete, class: "btn btn-secondary"%>
</div>

</div>
</div>

app/views/rentals/_form.html.erb
<div class="d-flex justify-content-center">
  <div class="card" style="width: 400px;">
    <div class="card-body">
      <h5 class="card-title"></h5>

<%= form_with(model: rental) do |form| %>
  <% if rental.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
        <% rental.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, "Cliente", style: "display: block" %>
    <%= form.collection_select :client_id, Client.all, :id, :name, prompt: "Seleccione un cliente" %>
  </div>

  <div>
    <%= form.label :movie_id, "Película", style: "display: block" %>
    <%= form.collection_select :movie_id, Movie.all, :id, :name, prompt: "Seleccione una película" %>
  </div>

  <div class="d-flex justify-content-between">
          <%= form.submit "Guardar", class: "btn btn-primary" %>
          
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/rentals/_rental.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 20vh;">
  <div class="container">
  

<div>
  <p><strong>Cliente:</strong> <%= rental.client.name %></p>
  <p><strong>Película:</strong> <%= rental.movie.name %></p>
</div>
</div></div>

app/views/rentals/edit.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
  <div class="container">
    <h1 class="text-center">Editar Rentas </h1>

<%= render "form", rental: @rental %>


  </div>
</div>
 

app/views/rentals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Rentas de Peliculas</h1>

<%= link_to "Agregar nueva Renta", new_rental_path, class: "btn btn-success float-right mb-3" %>

<div class="d-flex justify-content-center">
  <div class="row justify-content-center align-items-center no-gutters">
    <%  @rentals.each do |rental| %>
      <div class="col-lg-2 px-">
        <div class="card" style="width: 90%;">
         
          <div class="card-body">
            <h6 class="card-title">Cliente: <%= rental.client.name %></h6>
            <p class="card-text">
              <span class="font-weight-bold">Pelicula en Renta: </span> <%= rental.movie.name %>
            </p>
            <a href="<%= edit_rental_path(rental) %>" class="btn btn-primary btn-sm">Editar</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rentals/new.html.erb
<h1>New rental</h1>

<%= render "form", rental: @rental %>

<br>

<div>
  <%= link_to "Back to rentals", rentals_path %>
</div>

app/views/rentals/show.html.erb
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
 
  <div class="container">

<p style="color: green"><%= notice %></p>

<%= render @rental %>

<div>

    <%= button_to "Eliminar esta Renta", @rental, method: :delete, class: "btn btn-secondary"%>

</div>
 </div>
</div>